### ISSUE TITLE
Diagnostics WG Summit - Feb 12-13, 2018 - Ottawa, ON Canada

### ISSUE THREAD

**Issue by mike-kaufman** [nodejs/diagnostics#121] opened 2017-11-15 21:42 UTC
# Diagnostics WG Summit
 - Feb 12-13, 2018
 - Ottawa, ON Canada
 - Location Details & Accommodations:  [2016 Ottawa_visitor_guide.pdf](https://github.com/nodejs/diagnostics/files/1532485/2016.Ottawa_visitor_guide.pdf)

# Proposed Agenda

**Day 1 - Feb 12 2017**

Key Themes - Part1
8:30 - 9:00   - Arrive and settle in
9:00 - 9:10   - Introductions
9:10 - 9:20  - End user perspectives (Netflix)
9:20 - 9:30   - Agenda review
9:30 - 10:00  - Post Mortem - priorities/issues

10:00 - 10:30 - break

Key Themes - Part 2
10:30 - 11:00 - Monitoring - priorities/issues
11:00 - 11:15 - Debugging - priorities/issues
11:15 - 11:30 - Platform neutrality/APIs
11:30 - 12:00 - Testing and Documenation

12:00 - 1:00  - Lunch

1:00 - 3:00   - Breakout 1
3:00 - 3:30   - Break
3:30 - 5:30   - Breakout 2
5:30 - 6:00   - Demo from James/Matteo

6:30          -	Dinner 

**Day 2 - Feb 13 2017**
9:00 - 11:00  - Breakout 3
11:00 - 1:00  - Breakout 4

1:00 - 2:00   - lunch

2:00 - 3:15   - Breakout review
3:15 - 3:30   - Break
3:30 - 5:00   - Breakout review continued, recap and actions

The agenda is structured as a review of the key themes related to Diagnostics in order
lay the context for for the more in depth breakout sections, the breakout sessions
themselves and then finally a review of the output from the breakout sections and creation of
an action plan going forward.

Attendees:

1. @mhdawson
1. @mcollina
1. @mike-kaufman
1. @Qard
1. @hashseed
1. @watson
1. @mrkmarron
1. @jasnell
1. @danielkhan
1. @komawar
1. @joyeecheung
1. @cjihrig 
1. @fhinkel
1. @jkrems
1. @ofrobots
1. @dshaw
1. @kjin
1. @aruneshchandra 
1. @hekike
1. @mmarchini 
1. @Flarna
1. @Hollerberg
1. @distracteddev
1. @apapirovski
1. @skaegi 
1. @Fishrock123

Doc to refine subtopics/discussion points:
https://docs.google.com/document/d/1mB3nrCOhgKPEpPebpUEBDZQse6yKX4vwuwj-RpAWXWI/edit?usp=sharing

**Comment by mhdawson** [comment] 2017-11-16 21:44
Will look into how to book a Room in our office in Ottawa and then suggest a date/time

**Comment by watson** [comment] 2017-11-18 10:39
I'm in California for work from the Feb 26th to Mar 6th

**Comment by danielkhan** [comment] 2017-11-18 15:16
Thank you for setting that up. I'll definitely attend if it's not in the last week of January. We should also ping @nodejs/post-mortem because if we merge, the summit would be a great kick off for that.

**Comment by mhdawson** [comment] 2017-11-21 22:59
To start the discussion.

@nodejs/diagnostics 
@nodejs/post-mortem 
@nodejs/tsc 

I would suggest we hold the summit on **Mon Feb 12 and Tue Feb 13** in Ottawa at the 
[IBM office](https://www.google.com/maps/place/3755+Riverside+Dr,+Ottawa,+ON+K1V+1B8,+Canada/@45.3405379,-75.6926413,17z/data=!3m1!4b1!4m5!3m4!1s0x4cce07d425099837:0xce60525975398ee!8m2!3d45.3405342!4d-75.6904473).  The weekends before/after include 
[Winderlude](https://www.ottawatourism.ca/ottawa-insider/winterlude/) if you like skating and the IBM office is close the airport if you want to just fly in/out.  **Please comment  as to wether you want to participate and if those those days work for you or not and we'll either confirm or iterate as necessary.**

I would suggest we structure discussion in terms of themes as we did at the first vm summit. 

The themes I'd have in mind (probably incomplete, please make additional suggestions) would be:

* Post mortem diagnosis
  * Core tooling that should be part of Node.js itself
    * heapdump generation
    * node report generation (light weight easy to consume dump)
    * core dump generation
  * Cor dump introspection
    * llnode, mdb, etc.
    * javascripts APIs
    * maintenance/automation of keeping required data up to date
 * What is missing ? 
   
* Monitoring
  * Asynchronous context tracking
    * Async Hooks
  * Tracing
    * Adding Node.js trace points
    * Flight recorder
  * Loader Hooks ?
  * Profiling
  * What else should Node.js have in order to support great monitoring

* Debugging
  * Not sure what we need to discuss on this front....

* Documentation/Guidance
  * Module developers guide (as discussed in VM summit in Germany)
  * How to investigate common issues

* Testing
  * We don't necessarily have good testing or visibility into the testing we do have
  * Diagnostics test pass/fail should be a release criteria ?

* Platform neutrality/APIs
  *  Expanding N-API to cover diagnostics APIs ?
  *  Platform neutral internal APIs

* What's missing
  * How does Node.js stack up against other languages in terms of diagnostics
  * Would be good to be able to capture what we have, what we need to work on and have deck to 
    position that Node.js is good from a diagnostics point of view (possibly after some work)


We can structure however we want but at the first vm summit we had the following general approach

* Morning of first day, discuss key themes as a group.  At the end of the morning identify groups that 
  want to break out to discuss specific themes
* Afternoon of first day/Morning of second day groups meet to discuss specific themes, make concrete 
  plans for next steps and start working on those steps.
* Afternoon of second day get back together as a full group and each sub-group presents an overview of 
  what they discussed/planned/completed.

Depending on the number of people we get and the interest in the themes it may or may not make sense to break out into sub-groups.

**Comment by jasnell** [comment] 2017-11-21 23:01
Definitely +1, glad to see this move forward. I'll definitely be there.

**Comment by jasnell** [comment] 2017-11-21 23:06
I will say that Feb 13th is not a great day as I would need to leave early in order to not be traveling on Feb 14th... which is problematic from a My-Wife-Will-Kill-Me-If-I'm-Gone-On-Valentines-Day perspective. That said, Feb 8-9 and Feb 19-23 are out for me also.

**Comment by dshaw** [comment] 2017-11-21 23:30
+1

**Comment by danielkhan** [comment] 2017-11-22 11:57
+1

**Comment by benjamingr** [comment] 2017-11-22 12:26
Would be amazing to see a push for a better postmortem story for `async` functions.

**Comment by mhdawson** [comment] 2017-11-22 14:15
@benjamingr I knew I was forgetting something. I had thought of that at one point but missed it when putting together the overview.

**Comment by mhdawson** [comment] 2017-11-22 14:17
@benjamingr added

```
Supporting Promises/async functions
```

under the post mortem section. If that's not what you had in mind just give me some text to add

**Comment by ofrobots** [comment] 2017-11-22 16:24
I'm tentative. I have other travel planned for the second half of Feb. I will be able to confirm closer to the date.

**Comment by jkrems** [comment] 2017-11-22 20:54
I'll be there and I'm pretty flexible about the dates.

**Comment by benjamingr** [comment] 2017-11-22 21:15
@mhdawson that's exactly what I meant, thank you for including and considering it.

**Comment by komawar** [comment] 2017-11-22 21:22
I would like to attend, prefer Feb.

**Comment by hashseed** [comment] 2017-11-24 07:38
I would like to attend as well.

**Comment by watson** [comment] 2017-11-24 14:24
Those dates sounds fine with me 👍

**Comment by mhdawson** [comment] 2017-11-24 14:38
@bmeurer FYI in case you have not seen this yet.

**Comment by bmeurer** [comment] 2017-11-24 18:39
I have seen this already, yes. Chatted with @hashseed today and we decided it makes a lot of sense for him to go, since he knows the relevant parts of V8 a lot better than I do. 👍

**Comment by watson** [comment] 2017-11-24 18:48
How soon can we settle on dates? I'd prefer to buy plane tickets and book hotel before it gets too expensive 😃

**Comment by mhdawson** [comment] 2017-11-24 20:16
@watson, would a target of agreeing by mid-to-end next week work ?   

So far it sounds like my proposed dates are ok but was thinking we should give it a few more days given the Thanksgiving weekend in the US.

**Comment by watson** [comment] 2017-11-24 22:08
Absolutely, no problem 😃

**Comment by kjin** [comment] 2017-11-28 14:50
+1, mid-February would be great.

**Comment by fhinkel** [comment] 2017-12-04 11:38
I'll probably be joining, too. Are the dates set yet?

**Comment by cjihrig** [comment] 2017-12-04 14:12
These dates work for me.

**Comment by mhdawson** [comment] 2017-12-04 17:23
We are pretty much set on Mon Feb 12 and Tue Feb 13.  I have a room booked that should hold 20.  I just want to take a look at it tomorrow when I'm in the office and then I will comment here confirming.

**Comment by dshaw** [comment] 2017-12-04 21:08
@mike-kaufman Once @mhdawson gives the final go ahead, can you please update the issue with the final dates so folks can start booking travel?

If anyone needs travel assistance, please request here:
https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md

**Comment by joyeecheung** [comment] 2017-12-05 06:01
I am tentative to be there and discuss about post-mortem stuff, although I don't think my employer is going to sponsor the trip..

**Comment by mhdawson** [comment] 2017-12-05 18:41
Room looks good so we are set for Feb 12, 13.

**Comment by mhdawson** [comment] 2017-12-05 18:42
I work on a more detailed agenda over the next week so if you have any additional suggestions for topics please let me know.

**Comment by mike-kaufman** [comment] 2017-12-05 18:49
@mhdawson  - would be great if you could update issue summary at top to provide address/location so ppl can book convenient hotels.  We should fill in agenda there too when it firms up.

**Comment by mhdawson** [comment] 2017-12-05 18:51
Visitor guide with address, location info as well as hotel info.

[2016 Ottawa_visitor_guide.pdf](https://github.com/nodejs/diagnostics/files/1532485/2016.Ottawa_visitor_guide.pdf)

**Comment by mcollina** [comment] 2017-12-06 08:34
I hope to be able to attend!

**Comment by Qard** [comment] 2017-12-06 22:33
I, too, am hoping to attend. 👌

**Comment by hashseed** [comment] 2017-12-07 06:09
Already booked my flight. Do I need to register myself anywhere?

**Comment by watson** [comment] 2017-12-07 10:25
I plan to fly in the day before (maybe before) and leaving the day after

**Comment by mhdawson** [comment] 2017-12-07 22:38
Indicating here, should be enough.  I'll check into what info I need in terms of getting badges etc and then follow up in this issue.

**Comment by mrkmarron** [comment] 2017-12-08 05:31
I will plan to attend as well.

**Comment by jasnell** [comment] 2017-12-08 18:45
ping @mhdawson ... @mcollina and I would like to grab 30 minutes in the schedule to demo a few bits we've been working on with @AndreasMadsen

**Comment by mhdawson** [comment] 2017-12-11 21:08
@jasnell ack.

**Comment by danielkhan** [comment] 2017-12-11 21:30
I'll come as well.

**Comment by mcollina** [comment] 2017-12-12 10:26
At what time will we be finishing on the 13th?

**Comment by mhdawson** [comment] 2017-12-12 14:23
@mcollina I was thinking we use the 2 days, something like 9-5 each day, but open to other suggestions if people think something different would make sense.

**Comment by watson** [comment] 2017-12-18 16:02
Flights booked: I'll arrive Sunday and fly out again Wednesday

**Comment by Qard** [comment] 2017-12-19 17:23
Same. 🎉

**Comment by komawar** [comment] 2017-12-19 18:40
I intend to attend

**Comment by mhdawson** [comment] 2018-01-02 20:56
Proposed agenda. I leave a few days for comments and then pull up into the body of the isssue above:

Proposed Agenda

**Day 1 - Feb 12 2017**

Key Themes - Part1
8:30 - 9:00   - Arrive and settle in
9:00 - 9:20   - Introductions
9:20 - 9:30   - Agenda review
9:30 - 10:00  - Post Mortem - priorities/issues

10:00 - 10:30 - break

Key Themes - Part 2
10:30 - 11:00 - Monitoring - priorities/issues
11:00 - 11:15 - Debugging - priorities/issues
11:15 - 11:30 - Platform neutrality/APIs
11:30 - 12:00 - Testing and Documenation

12:00 - 1:00  - Lunch

1:00 - 3:00   - Breakout 1
3:00 - 3:30   - Break
3:30 - 5:30   - Breakout 2
5:30 - 6:00   - Demo from James/Matteo

6:30          -	Dinner 

**Day 2 - Feb 13 2017**
9:00 - 11:00  - Breakout 3
11:00 - 1:00  - Breakout 4

1:00 - 2:00   - lunch

2:00 - 3:15   - Breakout review
3:15 - 3:30   - Break
3:30 - 5:00   - Breakout review continued, recap and actions


The agenda is structured as a review of the key themes related to Diagnostics in order
lay the context for for the more in depth breakout sections, the breakout sessions
themselves and then finally a review of the output from the breakout sections and creation of
an action plan going forward.

Attendees:
@mhdawson
@mcollina
@mike-kaufman
@Quard
@hashseed
@watson
@mrmarron
@jasnell
@danielkhan
@komawar
@joyeecheung
@chihrig
@fhinkel
@jkin
@jkrems
@benjamingr
@ofrobots
@dshaw
@kjin



Current list of subtopics:

**Post mortem diagnosis**

Core tooling that should be part of Node.js itself
heapdump generation
node report generation (light weight easy to consume dump)
core dump generation
Core dump introspection
llnode, mdb, etc.
javascripts APIs
maintenance/automation of keeping required data up to date
Supporting Promises/async functions
What is missing ?

**Monitoring**

Asynchronous context tracking
Async Hooks
Tracing
Adding Node.js trace points
Flight recorder
Loader Hooks ?
Profiling
What else should Node.js have in order to support great monitoring


**Documentation/Guidance**

Module developers guide (as discussed in VM summit in Germany)
How to investigate common issues

**Testing**

We don't necessarily have good testing or visibility into the testing we do have
Diagnostics test pass/fail should be a release criteria ?
Platform neutrality/APIs

**Platform neutrality/APIs**
Expanding N-API to cover diagnostics APIs ?
Platform neutral internal APIs

**Comment by benjamingr** [comment] 2018-01-03 10:11
Hey, I would have loved to attend but I don't have the time off and it would be immediately after a lengthy(ish) vacation - so I won't be able to attend.

I would love to see the promise/post-mortem-debugging story improve as well as discussion of instrumentation. I'd love to see discussion between V8 people (such as @hashseed ) and people who have a stake in post-mortem debugging discuss what can be done about promises.

**Comment by watson** [comment] 2018-01-03 15:07
@mhdawson `s/Quard/Qard/`

**Comment by mike-kaufman** [comment] 2018-01-06 17:13
@mhdawson - Thank for putting agenda together.  Let's discuss on next Diag WG call.  There's a few things that I'm not 100% clear on (e.g., "flight recorder").  Also, I was thinking it would be helpful (at least to me) to get to "next level" detail on the agenda items (e.g., list of related issues, key themes/problems explicitly called out, desired outcomes from summit).  I wanted to check w/ others if they thought this useful as well & if so, best approach to get there.  Chime in here, or we can discuss on Jan 10 call.

**Comment by mike-kaufman** [comment] 2018-01-06 17:14
@mhdawson  - `s/mrmarron/mrkmarron`

**Comment by ofrobots** [comment] 2018-01-09 02:47
I can confirm that I will be able to make it to the Summit 🇨🇦 🎉.

**Comment by mhdawson** [comment] 2018-01-09 14:29
@ofrobots great to hear it :)

**Comment by mmarchini** [comment] 2018-01-09 19:42
Can anyone attend or just WG members? I'm interested but still not sure if I'll be able to go

**Comment by mhdawson** [comment] 2018-01-09 20:29
There are already a number of people who are not members of the Diagnostics WG attending.  From my perspective its open to anybody with a passion for Node.js and/or Diagnostics :)  (of course the room only holds so many people, but we still have space at this point)

**Comment by hekike** [comment] 2018-01-10 06:53
I'm interested as well. Could you please put me on the list if it's not too late?

**Comment by danielkhan** [comment] 2018-01-10 08:13
I might bring one or two co-workers who are working on our instrumentation.
Decision will be made until end of week.

**Comment by watson** [comment] 2018-01-10 09:56
Can people still apply for the travel fund? /cc @AndreasMadsen

**Comment by AndreasMadsen** [comment] 2018-01-10 22:18
From the meeting:

**We need to collaborate better on `trace_event` and `pref_hooks`**

There are features missing in `trace_events` that prevent us from relaying events from `pref_hooks` to `trace_events`. A fix for this is in progress.

My concern is that once we expose a `trace_event` API we will have two APIs for tracepoints. I see the `trace_events` as a clearly superior API.
* It supports time intervals directly and not just point-in-time marks
* It supports categories which are important for performance when a lot of tracepoints are exposed
* It outputs to a file in a very fast. From my experience collecting and analyzing data in the same process is a bad idea, as analyzing the data can easily interfere with performance.

I can understand the purpose of the `pref_hooks` API from the browser perspective because in the browser it is not possible to save the data to a file and analyze it later.

**Comment by jasnell** [comment] 2018-01-10 22:24
Yes, trace events are much more complete, which is why the goal is to integrate the two and ensure that perf entries can appear appropriately within the trace event timeline. perf_hooks serves a very specific and much narrower purpose but the two are easily usable together.

**Comment by mmarchini** [comment] 2018-01-11 11:07
I'll be able to make it if there's still space :smile:

**Comment by AndreasMadsen** [comment] 2018-01-11 15:51
@jasnell Could you clarify what "very specific and much narrower purpose" `perf_hooks` serves in a short post.

**Comment by mike-kaufman** [comment] 2018-01-11 15:58
@AndreasMadsen, @jasnell - does it make sense to fork the perf_hooks/trace_events discussion into a seperate issue?

**Comment by jasnell** [comment] 2018-01-11 16:02
Yep, it doesn't belong in this thread :)

**Comment by mhdawson** [comment] 2018-01-11 20:38
@hekike done.

**Comment by mhdawson** [comment] 2018-01-11 20:40
@mmarchini  added you to the list.

**Comment by hekike** [comment] 2018-01-12 08:07
@mhdawson thanks! See you there!

**Comment by jkin** [comment] 2018-01-14 04:31
@mike-kaufman Hello. I am not part of node.js development; not sure how my name got added. Will you please remove me from the list? Thank you.

**Comment by mhdawson** [comment] 2018-01-15 15:24
@jkin sorry about that, most likely my fault.  I pulled the list from the issue and I must have type one of the ones incorrectly.  Removed.

**Comment by danielkhan** [comment] 2018-01-16 09:59
@mhdawson could you please add @flarna and @GernotReisinger. They are members of our agent team.

**Comment by Hollerberg** [comment] 2018-01-16 10:22
@mhdawson - I could not resist to change my handle from @GernotReisinger to  @Hollerberg. Sorry for inconvenience.

**Comment by mhdawson** [comment] 2018-01-17 21:15
@danbev Done.

**Comment by mhdawson** [comment] 2018-01-17 21:15
@danielkhan done.

**Comment by dshaw** [comment] 2018-01-17 23:09
I'm in the process of kicking off the agenda building document for the Collaboration Summit at JSConfEU and I have to give props to @mike-kaufman and @mhdawson for an exceptionally well managed thread. 🙏 Thank you.

Of particular note:
1) Each individual comment was addressed. That's a nice experience for the folks requesting to join.
2) The original post (OP) has been actively updated throughout this process to capture the context folks who come here need most.

**Comment by danielkhan** [comment] 2018-01-24 20:28
To make it easier to collaborate on the agenda, I've created a doc for it: https://docs.google.com/document/d/1mB3nrCOhgKPEpPebpUEBDZQse6yKX4vwuwj-RpAWXWI/edit?usp=sharing

Together with @flarna and @hollerberg I've added some talking points to the monitoring chapter.

**Comment by mhdawson** [comment] 2018-01-29 21:19
@danielkhan thanks for the updates.  

@yunong from Netflix asked if they could provide their perspective (5 mins up front) as a heavy Node.js with a keen interest in Diagnostics.

I think it would be a good way to start by hearing from one of the heavy users.  If there are other attendees that would like to do the same I think that would also make sense.

Any objections to be adding this at the start of the agenda ?

**Comment by jasnell** [comment] 2018-01-29 21:20
I'm definitely +1 on yunong's request

**Comment by cjihrig** [comment] 2018-01-29 21:22
> Any objections to be adding this at the start of the agenda ?

Sounds like a good idea. +1 from me.

**Comment by distracteddev** [comment] 2018-01-30 22:26
Is it too late to add myself + another possible attendee to the list?

**Comment by mhdawson** [comment] 2018-01-30 22:39
@distracteddev we are getting close to the limit, but still enough room to add you. I think there should be room for a couple more,  but I should probably check the room.

I've added you to the list of attendees.

**Comment by apapirovski** [comment] 2018-01-31 14:56
@mhdawson I would love to attend since it's but a short drive from Toronto but I'm not 100% certain I'll be around then. I'm currently in the middle of a move to the Bay area and my actual moving dates are very uncertain. Still, any chance I could be added to the list?

**Comment by mhdawson** [comment] 2018-02-01 18:28
@apapirovski added.

**Comment by gabrielschulhof** [comment] 2018-02-01 19:18
I'm also going to do my best to attend. Hope to see y'all there!

**Comment by mhdawson** [comment] 2018-02-01 19:20
@gabrielschulhof I've added you.  At this point I think we are pretty much at capacity but I'll check out the room tomorrow.  If anybody on the list knows they cannot make please comment so that we know there is some additional free space.

**Comment by mhdawson** [comment] 2018-02-05 14:10
@gabrielschulhof mentioned he won't be able to make it after all.  Removed him from the list.

**Comment by mhdawson** [comment] 2018-02-05 21:28
@yunong updated agenda to include time for end users to present their perspective up front, with slot for Netflix.

**Comment by mhdawson** [comment] 2018-02-06 15:51
@mhdawson
@mcollina
@mike-kaufman
@Qard
@hashseed
@watson
@mrkmarron
@jasnell
@danielkhan
@komawar
@joyeecheung
@cjihrig
@fhinkel
@jkrems
@ofrobots
@dshaw
@kjin
@aruneshchandra
@hekike
@mmarchini
@Flarna
@Hollerberg
@distracteddev
@apapirovski

For Wifi access can each of you send me the following information (via my email in my GitHub profile) with the following info so I can make the appropriate request:

First Name
Last Name
Email address
Company

**Comment by skaegi** [comment] 2018-02-07 03:50
@mhdawson Although not a member of the WG I'm in Ottawa and would also like to attend. I'm currently part of TC39 (though less involved now) and can offer some perspective having both written a JavaScript debugger and participated in earlier efforts to standardize a JavaScript Debug Protocol.

**Comment by mhdawson** [comment] 2018-02-07 14:33
@skaegi added. Looking forward to seeing you there.

**Comment by mhdawson** [comment] 2018-02-07 15:01
@mhdawson
@mcollina
@mike-kaufman
@Qard
@hashseed
@watson
@mrkmarron
@jasnell
@danielkhan
@komawar
@joyeecheung
@cjihrig
@fhinkel
@jkrems
@ofrobots
@dshaw
@kjin
@aruneshchandra
@hekike
@mmarchini
@Flarna
@Hollerberg
@distracteddev
@apapirovski
@skaegi 

I've made a reservation for Monday at 6:30 at a pub that is a short walk down the street from the office.  They tell me the menu is typical pub food and there are a few vegetarian options.  I've assumed most people will want to come along but they would like a good estimate of the number of people so can each of you use the thumbs up/down to confirm if you will be coming.   I only have the budget for lunch so we'll each be on our own to cover the cost of dinner.

**Comment by Fishrock123** [comment] 2018-02-09 16:01
Heya - there was a bit of a planning snafu but it looks like I’ll be making my way up, one way or other.

@mhdawson could you add me to that? Thanks!

**Comment by mhdawson** [comment] 2018-02-09 16:22
@Fishrock123 added.

**Comment by apapirovski** [comment] 2018-02-11 13:21
@mhdawson  Unfortunately I have to cancel at the last minute. A few of my move-related appointments ended up falling on Tuesday and I can't reschedule. 😞

**Comment by watson** [comment] 2018-02-11 16:18
Unfortunately Air Canada have canceled my flight due to snow in Ottawa. They have put me on a flight tomorrow instead, but it doesn’t land in Ottawa until 9:52am. I’ll just take a taxi directly to the office, so hopefully I’ll be there before 11 depending on how difficult immigration is

**Comment by Fishrock123** [comment] 2018-02-11 23:41
Is anyone else staying in the Hilton Garden Inn and want to meet up tonight?

**Comment by Qard** [comment] 2018-02-11 23:48
I'm downtown at the Marriott. I'm happy to meet anyone downtown though.

**Comment by mhdawson** [comment] 2018-02-12 01:40
@apapirovski, sorry to hear to you can't make it.

**Comment by mhdawson** [comment] 2018-02-12 01:41
@watson, sorry to hear that.  The weather has been a bit fun today with freezing rain, we'll be lucky if you are the only.

**Comment by mhdawson** [comment] 2018-02-12 13:19
Link for hangout for part 1 . https://hangouts.google.com/hangouts/_/ytl/VvCuESyw0kopVKT20PYT4-c4sSd2dcwSiUUxpUGtiHQ=?eid=100598160817214911030

**Comment by mhdawson** [comment] 2018-02-12 13:25
Doc for minutes https://docs.google.com/document/d/1jS_s_ebaDK0E-axbInTU8wIv51up9Kufdsav1SGSWz0/edit

**Comment by joyeecheung** [comment] 2018-02-12 14:37
Gist on llnode update: https://gist.github.com/joyeecheung/3d732fc854af1e1b22313e3a9e9a8f2a

**Comment by mmarchini** [comment] 2018-02-12 16:08
The`core to heap dump` tool I've been working on: 
https://github.com/mmarchini/llnode/tree/core-to-snapshot

Also, a quick video demonstrating how it works: 
https://www.youtube.com/watch?v=ou4i5vw70eg

**Comment by mhdawson** [comment] 2018-02-12 17:16
Will post new meeting link once we start up again after lunch.

**Comment by komawar** [comment] 2018-02-12 19:58
@mhdawson do you guys have a link for the next part of hangout?

**Comment by mhdawson** [comment] 2018-02-12 21:07
Sorry here it is, a bit late

https://hangouts.google.com/hangouts/_/ytl/4Svka3GsZ-4V-iquyKYwqgwPSfayPgEi76zfvgphhWg=?eid=100598160817214911030

**Comment by mhdawson** [comment] 2018-02-12 22:17
![p_20180212_110507_vhdr_on 1](https://user-images.githubusercontent.com/9373002/36122744-7cc8cfe2-1018-11e8-8bd9-8f3692487e87.jpg)

**Comment by hekike** [comment] 2018-02-12 22:19
@yunong's CPU Profiling Roadmap: https://github.com/nodejs/diagnostics/issues/148

**Comment by mhdawson** [comment] 2018-02-12 22:19
![p_20180212_134720_vhdr_on 1](https://user-images.githubusercontent.com/9373002/36122869-e88582ca-1018-11e8-95b5-0e02611b50b8.jpg)

![p_20180212_134717_vhdr_on 1](https://user-images.githubusercontent.com/9373002/36122856-dee565dc-1018-11e8-8405-4b8e3ac94664.jpg)

![p_20180212_121140_vhdr_on 1](https://user-images.githubusercontent.com/9373002/36122840-d416902c-1018-11e8-8209-f552eae3663d.jpg)

![p_20180212_121139_vhdr_on 1](https://user-images.githubusercontent.com/9373002/36122824-ca642224-1018-11e8-9c7b-759a45c3c712.jpg)

![p_20180212_113742_vhdr_on 1](https://user-images.githubusercontent.com/9373002/36122795-b3a99758-1018-11e8-9ed8-a860a6cea373.jpg)

![p_20180212_113737_vhdr_on 1](https://user-images.githubusercontent.com/9373002/36122789-abd7595c-1018-11e8-9ca9-28cf99577a5e.jpg)
![p_20180212_110507_vhdr_on 1](https://user-images.githubusercontent.com/9373002/36122779-a2d0dfea-1018-11e8-9661-6a0a68f8a235.jpg)
![p_20180212_121136_vhdr_on 1](https://user-images.githubusercontent.com/9373002/36122810-c0851f06-1018-11e8-86e1-26cd982b5dde.jpg)

**Comment by mmarchini** [comment] 2018-02-13 13:19
@mcollina can you share the pictures from the first Breakout, with the use cases and dream tools?

**Comment by mhdawson** [comment] 2018-02-13 13:37
Link for day 2 https://hangouts.google.com/hangouts/_/ytl/4UTqREWcIX6SSUN-sFNcY1xTi31kYHxDDVmVOqs4b1U=?eid=100598160817214911030

**Comment by mcollina** [comment] 2018-02-13 14:34
![use cases](https://user-images.githubusercontent.com/52195/36154916-e9e53ea2-10a0-11e8-9c1e-e9879ec3fa9f.png)
![my app is slow](https://user-images.githubusercontent.com/52195/36154914-e9c5f42a-10a0-11e8-916c-4d36d5a4fea4.png)
![unexpected memory usage](https://user-images.githubusercontent.com/52195/36154962-0bfaab12-10a1-11e8-8ded-b9e1193196d0.png)

**Comment by mike-kaufman** [comment] 2018-02-13 19:46
Monkey Patching Discussion live-stream:  http://youtu.be/W2rVLXr9WFU

**Closed** 2018-02-21 21:35 UTC
Labels: diag-agenda
