### ISSUE TITLE
Need way to distinguish actual before/after calls from 'new-child' before/after calls

### ISSUE THREAD

**Issue by ofrobots** [nodejs/diagnostics#13] opened 2015-03-26 16:26 UTC
Looking at the code (and example tests), the current semantics for async_wrap seem to be that the before/after hooks are called from two places
* before and after the application of the async callback (i.e. the intuitive place): https://github.com/iojs/io.js/blob/0af4c9ea7434e4f505dbe071357e4bc3b4ab2a8a/src/async-wrap.cc#L112
* when a child async object is being created, the parent's before and after hooks get called. https://github.com/iojs/io.js/blob/v1.x/src/async-wrap-inl.h#L35-L37

I cannot seem to figure out a way to distinguish between these two cases. When the hook gets called, I am not sure if the event is actually getting processed or a child event got instantiated. Am I missing something?

Would it make sense to have 5 hooks: init, before, after, child_before, child_after? @trevnorris 

~~Here's a sample program: https://gist.github.com/ofrobots/59bb54ef677834443672
The before/after hooks for context with uid 1 get called multiple times.~~
EDIT: Here's a better test-cased based on the blog post:  https://gist.github.com/ofrobots/d725e7c2aa5fdafa8a13

**Comment by trevnorris** [comment] 2015-03-26 17:08
The simplest solution is to pass an argument to the callback. On the list is a plan to pass the `PROVIDER` type to the callbacks, which could be easily overloaded so you could detect this case as well.

**Comment by Qard** [comment] 2015-03-26 17:15
What if the `PROVIDER` value is the same?

I'm curious what the intended purpose is to having those before/after hooks around child async creation. Can those not be named differently? Do those even need to be there? What would they be used for?

**Comment by ofrobots** [comment] 2015-03-26 17:23
I see value in being able to string together the parent-child relationship to show causality. But some people might not care. If these are separate hooks, then people could opt out of these extra events and avoid unnecessary callbacks.

**Comment by Qard** [comment] 2015-03-26 17:30
Can that not be done by storing a context id in the before handler and checking that value in the child init handlers?

**Comment by ofrobots** [comment] 2015-03-26 18:04
Yes, you can establish parent-child relationship that way if the parent's hooks get called around child's init. In the example I linked to above, the parent's (1) before hook isn't applied (for real) until after child's (2) init.

**Comment by Qard** [comment] 2015-03-26 18:18
I think that is mostly a perception issue. Nothing is truly "async" until it jumps the barrier into C++, at which point you no longer have anything that could occur between the init and before events.

I think patching of abstractions over truly async things should simply acknowledge that they themselves are not actually async and simply establish the boundary linking through the thing they abstract.

**Comment by trevnorris** [comment] 2015-03-26 19:36
@Qard 
> Nothing is truly "async" until it jumps the barrier into C++

The problem is when the starting point is C++. The code is to cover cases where a connection is received, and you want to be able to trace the connection back to the server which received it. Since the connection comes from C++ it has no stack above it so there is no way to store any properties elsewhere which would let you know where it's coming from.

**Comment by Qard** [comment] 2015-03-26 20:39
Ah, yes. That is an interesting case.

Ultimately what we want is linking between the *call* and the callback, but async_wrap provides linking between *resource creation* and the callback. This style is useful for potentially tracking and cleaning up resources, but doesn't necessarily get us the JS -> C++ -> JS boundary linking we want without the extra weirdness of the before/after events getting triggered around child inits.

I would definitely suggest using different named events for those to not be ambiguous. I would also suggest placing triggers that wrap the sync execution of calls into C++ and around the sync execution of JS callbacks. This encapsulates the sync boundary jumps from JS into C++ (calls) and from C++ into JS (callbacks). Then you just need a mechanism of linking the callbacks to their originating calls.

**Comment by trevnorris** [comment] 2015-03-26 21:38
I'm trying to recall why I'm allowing the user to handle this case, as I'm sure there was a reason. ATM seems I could have handled that automatically instead. I'll investigate.

**Comment by trevnorris** [comment] 2015-06-16 22:37
@Qard The calling of `before`/`after` in `init` has been fixed by https://github.com/nodejs/io.js/commit/7dde95a8bd.

**Comment by trevnorris** [comment] 2015-06-16 22:46
@ofrobots The `init` callback in the most recent API is `function init(provider)`. A possibly more elegant solution is `function init(provider, parent = null)`, where the parent object is passed, if there is one. Thoughts?

**Comment by ofrobots** [comment] 2015-06-17 17:07
@trevnorris Yes I saw those changes and have been prototyping with them already, thanks. :+1: on the parent object being passed to the init function if available.

**Comment by AndreasMadsen** [comment] 2015-10-08 15:36
@ofrobots @trevnorris This issue can be closed, right?

**Closed** 2016-06-08 07:03 UTC
